### ISSUE TITLE
Shuffling the answers of a question

### ISSUE THREAD

**Issue by FranckRENAUD** [nennigb/amc2moodle#1]
Hello,

Your tool is very useful and time saving. Still, when importing the xml file to moodle, the box for automatic shuffle of the answers is not checked.

Please consider adding the following code to the xml file : `<shuffleanswers>true</shuffleanswers>`

Thanks

**Comment by nennigb** [comment]
Thank you for your comment.
Answers are now shuffled. If needed, the behavior can be changed in grading.py by setting 
`ShuffleAll = False '
