### ISSUE TITLE
Problems with  mhchem package

### ISSUE THREAD

**Issue by rborrelli** [nennigb/amc2moodle#10]
Hi,
thanks for this very nice code. I am trying to use it with my test but I have a lot of chemical formulae written using the package mhchem which is quite used for chemical notations. Is it possible to add some biding for this package? The syntax is quite simple, it introduces a new latex environment "\ce{}" in which the chemical formulae or equation is typed. For example
\ce{H^+} gives a result simular to $\mathrm{H}^+$.
At the moment amc2moodle complains that the symbol ^ can be used only in math mode so I get an XML file full of errors.
Is it possible to solve or at least bypass the problem?

Thanks,
Raffaele

**Comment by nennigb** [comment]
Hi, 
thanks a lot. Could you attached a minimal example to reproduce the problem (header and 1 question)?

Benoit

ps : have you try the new version (as a python package)

**Comment by rborrelli** [comment]
Hi,
thanks for the answer, unfortunately my chemistry exams are full of chemical formulae written with mhchem, and I do not have the possibility to install mhchem on the server (I should ask the IT administrator to do it). Looking at the status of latexml it seems that version 0.8.4 should support mhchem, am I wrong?

Thanks
Raffaele

**Comment by nennigb** [comment]
Hi,

Enabling `mhchem` in mathjax is very simple, I have tried it yesterday on [moodle sandbox server](https://sandbox.moodledemo.net/login/index.php) and it works fine (but you need to be admin). **It means that even if amc2moodle is not yet ready for processing your question using `mhchem`, you can still make your exam on moodle (with moodle html interface) without changing too much your quizz structure.**
The procedure for your IT is given here : https://docs.moodle.org/38/en/Chemistry_notation_using_mhchem
it takes two minutes. The link contains also some examples and usages.

As far as I have read, mhchem support is planned for LaTeXML 0.9 version (next release).

I will contact LaTeXML team to find a solution.

Benoit

**Comment by rborrelli** [comment]
Thanks,
meanwhile I have managed to devine a new environment \ce{}  which actually works as \mathrm, I only have to do some changes to my formuale, but it's a minor issue. It works fine. The only problem is that when I have a something like
\begin{itimize} 
\item[I] XXX
\item[II] YYY
\end{itemize}
the labels of the items, I and II disappear from the xml file. Is his normal?
Thanks,
Raffaele

**Comment by nennigb** [comment]
I am happy to see you find a workarround.
There is a typo in your itemize (itimize), but you are right, this environment is not properly parse by amc2moodle for html rendering. I will correct this asap.
Nonetheless, itemize without [] can produce a list without bullet even it is not perfect. You can edit your question in moodle editor.

I will try to o a little bit further with mathjax approach.

Benoit

**Comment by nennigb** [comment]
The problem with itemize is now solved. You could try it on switching in feature-itemize branch.
Remarks : tag in `\item[tag]` are not supported. It seems not possible to change the bullet in html...
Let me know if it works properly.

Benoit

**Comment by nennigb** [comment]
Hi,

I have made the modification to support `mhchem` through `mathjax`. If you want, you could try it on the branch feature-mhchem. The procedure for your IT is given [here](https://docs.moodle.org/38/en/Chemistry_notation_using_mhchem) and in the [amc2moodle README file](amc2moodle/amc2moodle/README.md).

Benoit

**Comment by rborrelli** [comment]
Hi, sorry for the late reply. I will check with the IT if they can install mhchem.
Thanks for the effort.
