### ISSUE TITLE
NOT numbering of moodle answers

### ISSUE THREAD

**Issue by adl** [nennigb/amc2moodle#18]
When I use AMC, each possible choice has a box to tick, and these choices are not numbered.

Testing `amc2moodle` on a small example, I see that each possible answer gets numbered (a, b, c, ...).
This can be quite confusing.  Consider:

> What is the first letter of the alphabet?
>
> Select one:
> ◯ a. b
> ◯ b. z
> ◯ c. a

Clearly I'd prefer to see

> What is the first letter of the alphabet?
>
> Select one:
> ◯ b
> ◯ z
> ◯ a

How do you feel about forcing [`<answernumbering>none</answernumbering>`](https://docs.moodle.org/38/en/Moodle_XML_format#Multiple_choice) for all questions?

**Comment by nennigb** [comment]
Hi,

you're right, the main different formats are
```
<answernumbering>123</answernumbering>
<answernumbering>ABCD</answernumbering
<answernumbering>abc</answernumbering> (the default choice)
<answernumbering>iii</answernumbering>
<answernumbering>none</answernumbering>
```
basically, you will need to modify `amc2moodle/amc2moodle/convert.py`
```
# create an option at the begining
answerNumberingFormat = 'none'  # choose in '123', 'abc', 'iii', 'none', 'ABCD' 

# in the loop at l. 317 (simple question)
answernumbering = etree.SubElement(Qi, "answernumbering")
answernumbering.text = answerNumbering
```
and do the same in the loop starting at l. 374 (questionmult).

Tell me if it is working. We will need to cleanup all these options one day... 

Benoit
