### ISSUE TITLE
Problem for installing in Mac (Mojave)

### ISSUE THREAD

**Issue by nennigb** [nennigb/amc2moodle#2]
Hi,

Feel free to ask your questions here :
  - on the usage
  - on bugs
  - ...

In case of trouble during the conversion, put the command line output to help to locate the origin of the problem.

nennigb

**Comment by stef30360** [comment]
Pourriez vous m'expliquer l'installation convenant les deux items ci-dessous ... je suis fragile en informatique
merci
Install :

• Create a link in /usr/bin or add to the execution amc2moodle root path the folder.

• Set the src folder in the amc2moodle.sh script or modify it to take into account an environment variable.

**Comment by nennigb** [comment]
Bonjour,

Une fois le programme dézippé, si vous souhaitez y avoir accès quelque soit le dossier dans lequel votre terminal est ouvert, vous devez créer un lien symbolique (sorte de raccourcis) avec la commande `ln -s`. Cette étape est optionnelle. 
Vous pouvez aussi utiliser des variables d'environnement pour obtenir le même résultat.  Cette étape est aussi optionnelle. 

L’approche la plus simple est d'ouvrir un terminal dans le dossier où vous avez dézippé `amc2moodle`. Ce dossier contient `amc2moodle.sh`. Vous pouvez alors lancer la conversion depuis ce dossier directement en précisant les chemins vers vos fichiers amc au format latex:
```
./amc2moodle chemin_vers_fichier_amc/fichier_amc.tex
```
Vérifiez que le chemin ne contient pas d'accent. Pour le moment `amc2moodle` ne fonctionne que sous linux, vous devez aussi avoir installé les dépendances comme expliqué dans la doc.

Un bon moyen de vérifier que tout fonctionne correctement est de tester sur l'exemple `QCM.tex` du le dossier `test`.

Est-ce plus clair ?

Cordialement,

BN

**Comment by stef30360** [comment]
Bonjour, 
Très clair merci… je suis sous Mac Mojave… Je me bat pour installer la librairie PythonMagick sans succès…. Peut-être auriez vous une solution de substitution? (ImageMagick ???)
Cldt
SR

**Comment by nennigb** [comment]
Vous pouvez utiliser imageMagick pour convertir toutes les images appelées par le fichier tex en png avant d'utiliser `amc2moodle` (n'oubliez pas de modifier le fichier tex en conséquence). Dans ce cas vous n'aurez plus besoin de `pythonmagick`. Vous pourrez alors commenter dans `grading.py`:
```
from PythonMagick import Image
```
and
```
im = Image.open(pathF+ img_name +'.' + ext)
img_name = img_name + ".png"
im.write(pathF + img_name)
```
De même si vous n'avez pas de fichier image en pdf, vous pour utiliser PIL ou pillow pour les conversion, que vous pourrez installer (plus facilement) via pip.

Bon courage ;-)

BN

**Comment by stef30360** [comment]
Bonjour, 
Je reviens vers vous car j’ai me semble t-il une erreur de path…mais je ne vois pas ou ?
 (J’ai modifier le chemin dans le .sh )
src="/Users/srmojave/Projets-QCM/amc2moodle-master/src"
Donc...
Sous le répertoire "amc2moodle-master » (dezziper)
J’exécute le script avec le fichier Tex
Shell > srmojaves-iMac:amc2moodle-master srmojave$./amc2moodle.sh.  /Users/srmojave/Projets-qcm/amc2moodle-master/test/QCM.tex 

Cela me retourne ceci.

run with the defaut parameters
readlink: illegal option -- m
usage: readlink [-n] [file ...]
Parameters :
------------------------------------------
 >path input    :/
 >path output   :/
 >file input    :
 >file output   :.xml
 >keep temp     :0
 >use categorie :0
 >catname       :
 > Running LateXML conversion... 
latexml (LaTeXML version 0.8.4)
processing started Wed Mar 25 11:29:20 2020

Fatal:missing_file:// Can't find TeX file //
	search paths are /Users/srmojave/Projets-qcm/amc2moodle-master, /Users/srmojave/Projets-QCM/amc2moodle-master/src
1 fatal error

Conversion complete: 1 fatal error.
processing finished Wed Mar 25 11:29:20 2020
 > Running python conversion... 
Traceback (most recent call last):
  File "/Users/srmojave/Projets-QCM/amc2moodle-master/src/grading.py", line 42, in <module>
    from PythonMagick import Image
ImportError: No module named PythonMagick
 > Delete temp file : /tex2xml.xml
rm: /tex2xml.xml: No such file or directory
Error: Could not open '//.xml': No such file or directory.

    File converted. Check below for errors...

**Comment by nennigb** [comment]
Bonjour,

1. La définition de src semble ok, car il trouve bien grading.py. Je pense que le problème vient de 'projets-qcm' au lieu de 'projets-QCM' dans le chemin vers le fichier tex.

2. vous devez aussi commenter  ```from PythonMagick import Image```  -> ```# from PythonMagick import Image``` au début du fichier ```src/grading.py```

Cordialement,

BN

**Comment by stef30360** [comment]
Merci pour votre retour…
Non toujours même erreur … je ne comprend pas pourquoi l’erreur retourne «search paths are /Users/srmojave/Projets-QCM/amc2moodle-master » ...Can't find TeX file ….  je suis pourtant au bon endroit avec le bon path !!!

#From PythonMagick … a été commenté mais génère des pbs d’arguments


<shell>...

srmojaves-iMac:amc2moodle-master srmojave$ ./amc2moodle.sh /Users/srmojave/Projets-QCM/amc2moodle-master/test/QCM.tex



Fatal:missing_file:// Can't find TeX file //
	search paths are /Users/srmojave/Projets-QCM/amc2moodle-master, /Users/srmojave/Projets-QCM/amc2moodle-master/src
1 fatal error

Conversion complete: 1 fatal error.
processing finished Wed Mar 25 16:11:02 2020
 > Running python conversion... 
Problem with the number of imput args, check calling seq. in amc2moodle.sh .
 > Delete temp file : /tex2xml.xml
rm: /tex2xml.xml: No such file or directory
Error: Could not open '//.xml': No such file or directory.

**Comment by nennigb** [comment]
Vous pouvez essayer, peut-être avec l'autre syntaxe...
```
./amc2moodle.sh -i /Users/srmojave/Projets-QCM/amc2moodle-master/test/QCM.tex
```

**Comment by nennigb** [comment]
- Tout se passe comme si `/` était pris comme path...
- Essayer avec un chemin relatif 
```
./amc2moodle.sh -i ./test/QCM.tex
```
peut-être que le  `/` qui débute le chemin plante le découpage du chemin
- Vous pouvez aussi lancer séparément chaque ligne du script. Cela vous aidera sûrement à comprendre le problème

**Comment by stef30360** [comment]
fix it ! …..Je reviens vers vous… le malaise était plus profond. En fait le système GNU  et Mac (BSD) ne corresponde pas exactement…. Par conséquent dans le .sh la bibliothèque readlink  (option -m) généré une erreur. 

Le solution est la suivante:

Installer 
1 brew install coreutils
2 écrire les deux commandes dans le Shell suivantes:
# make GNU commands available
export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"

export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}"
 Voilà solution trouvé sous https://stackoverflow.com/questions/57972341/how-to-install-and-use-gnu-ls-on-macos

SR

**Comment by nennigb** [comment]
Bonne nouvelle,
Dites moi si la conversion fonctionne.
A terme, il faudrait éviter ce script et le passer en python (plus portable).
Je vais fermer clore le fil de discussion et le renommer pour aider les utilisateur sous mac.

Cordialement,
BN

**Comment by stef30360** [comment]
Bonjour, 
La conversion n’est pas optimale, notamment l’écriture mathématique qui n’est pas reconnu sur la plateforme  Moodle de l’université.
cldt
SR

**Comment by nennigb** [comment]
Aïe. Il faut que matjax soit activé sur moodle.

La conversion de certaines constructeurs de AMSmath ne fonctionneront pas à cause de la façon dont sont traitées les équations. 
>Put in-line equations like x 2 or use equation environment (or $$ delim-
iters). For the moment eqnarray or the amsmath environments multline,
align are not supported. The choice have been made to keep equation in
tex and use mathjax filter of moodle for rendering. In my opinion, it is
better for modifying question after importation.

Pourriez-vous m'envoyer un exemple représentatif (ici ou par email) pour que je test ?

**Comment by stef30360** [comment]
Exemple ?….j’ai utilisé l’exemple fournie dans la ressource QCM.xml

**Comment by nennigb** [comment]
Vous pouvez vérifier si mathjax est activé sur votre moodle, en allant sur
administration du cours\filtres
Vous pouvez tester que $$x^3 $$ fonctionne dans une question/section crée par l'interface graphique.

Je viens de vérifier, QCM.xml (https://github.com/nennigb/amc2moodle/blob/master/test/QCM.xml) peut-être chargé sans problème sur la sandbox de moodle (https://sandbox.moodledemo.net/)
Peut-être que votre fichier QCM.xml a eu un problème lors de la conversion... 
Quelle est la version de moodle à votre université ?

**Comment by stef30360** [comment]
Bonjour, 
Je vous joint les deux fichiers et la réponse du propriétaire de la ressource ... 

" ...Vous pouvez vérifier si mathjax est activé sur votre moodle, en allant sur 
administration du cours\filtres 
Vous pouvez tester que $$x^3 $$ fonctionne dans une question/section crée par l'interface graphique. 

Je viens de vérifier, QCM.xml ( [ https://github.com/nennigb/amc2moodle/blob/master/test/QCM.xml | https://github.com/nennigb/amc2moodle/blob/master/test/QCM.xml ] ) peut-être chargé sans problème sur la sandbox de moodle ( [ https://sandbox.moodledemo.net/ | https://sandbox.moodledemo.net/ ] ) 
Peut-être que votre fichier QCM.xml a eu un problème lors de la conversion... 
Quelle est la version de moodle à votre université ? " 

.... 

cldt SR 

> De: "moodle-assistance" <moodle-assistance@umontpellier.fr>
> À: "Stephane Reyes" <stephane.reyes@umontpellier.fr>
> Cc: "moodle-assistance" <moodle-assistance@umontpellier.fr>
> Envoyé: Jeudi 26 Mars 2020 15:41:24
> Objet: Re: amc et Moodle

> Pouvez-vous m'envoyer votre fichier xml généré et son fichier latex ?
> Quand je teste la génération le fichier d'exemple est tronqué.
> J'aimerai donc essayé avec votre fichier

> Agathe de l'équipe support

> [ https://moodle.umontpellier.fr/course/index.php?categoryid=2166 | Guide de
> survie numérique  ]
> [ https://moodle.umontpellier.fr/course/index.php?categoryid=345 | Tutoriels
> Moodle ]

>> De: "Stephane Reyes" <stephane.reyes@umontpellier.fr>
>> À: "moodle-assistance" <moodle-assistance@umontpellier.fr>
>> Envoyé: Mercredi 25 Mars 2020 11:52:34
>> Objet: Re: amc et Moodle

>> Bonjour,
>> premièrement il y a une erreur de frappe.....(remplacer ? par un . voir ci
>> dessous)

>> 2. le fichier QCM.xml du répertoire "test" de l'outil à télécharger [
>> https://github.com/nennigb/amc2moodle | https://github.com/nennigb/amc2moodle ]
>> renvoie sur moodle ceci

>> cldt
>> SR

>>> De: "moodle-assistance" <moodle-assistance@umontpellier.fr>
>>> À: "Stephane Reyes" <stephane.reyes@umontpellier.fr>
>>> Cc: "moodle-assistance" <moodle-assistance@umontpellier.fr>
>>> Envoyé: Mercredi 25 Mars 2020 11:15:11
>>> Objet: Re: amc et Moodle
>>> Bonjour,

>>> Pouvez-vous nous envoyer une copie de l'erreur s'il vous plait ?
>>> Cordialement

>>> Agathe de l'équipe support

>>> [ https://moodle.umontpellier.fr/course/index.php?categoryid=2166 | Guide de
>>> survie numérique  ]
>>> [ https://moodle.umontpellier.fr/course/index.php?categoryid=345 | Tutoriels
>>> Moodle ]

>>>> De: "Stephane Reyes" <stephane.reyes@umontpellier.fr>
>>>> À: "moodle-assistance" <moodle-assistance@umontpellier.fr>
>>>> Envoyé: Mardi 24 Mars 2020 17:35:50
>>>> Objet: amc et Moodle
>>>> Bonjour,
>>>> Le tutoriel ( [ https://moodle.umontpellier.fr/mod/page/view.php?id=78325 |
>>>> https://moodle.umontpellier.fr/mod/page/view.php?id=78325 ] ) qui permet
>>>> d’importer des QCM à partir de amc ne fonctionne pas ….le fichier xml exemple (
>>>> [ https://github.com/nennigb/amc2moodle | https://github.com/nennigb/amc2moodle
>>>> ] )génére une erreur.

>>>> Merci de me tenir informé

>>>> SR

**Comment by stef30360** [comment]
Je viens d’envoyer le.tex et le .xml aux service informatique de l’université…je reviens vers vous dès que j’ai un retour

Autre chose j’ai essayé un un qcm (goupevav.tex ci dessous) prenant en compte le package tikz.. mais la conversion est sans succès. Auriez vous une issu ?
Merci

**Comment by nennigb** [comment]
Bonjour, 
Le traitement du fichier latex est réalisé par latexml. Je crois que le support de tikz n'est pas complet. Mais j'avoue n'avoir jamais essayé. 
Pourriez-vous attacher à votre message une question de QCM utilisant tikz (je n'ai pas accès à votre moodle). 

Cordialement,

BN

**Comment by stef30360** [comment]
Je vous ai envoyé le .tex dans mon précédent mail ….

**Comment by nennigb** [comment]
Bonjour,

Nos échanges passent par le suivi de bugs de github. Vos pièces ont dues être supprimées.
Je vous invite à continuer cette discussion par email (l'adresse est dans le code amc2moodle).
Par ailleurs, il semble possible de prendre en compte tikz, je peux essayer de faire les modifs d'ici quelques jours.

Cordialement,

BN

**Comment by nennigb** [comment]
L'installation a été simplifiée en utilisant le gestionaire de packet python pip 
Les images sont traitées avec `wand` plus simple à installer sur MacOS.
Les tests sont maintenant aussi réalisés sur MacOS.
Pour tikz, c'est en standbye...
