### ISSUE TITLE
moodle2amc issue with accent text amd gift questions

### ISSUE THREAD

**Issue by pacoriviere** [nennigb/amc2moodle#38]
1. When converting moodle xml format to AMC tex, moodle2amc does not remove accented characters, from group and question names. These letters are accepted in moodle but not in AMC. amc2moodle should change, for example, an 'à' by an 'a'. Otherwise it is only useful in English and for other languages a painful revision must be done by hand.
2. When converting moodle xml format to AMC tex, options are only included in the output tex file if they are in [moodle] format. Moodle XML stores questions in two formats [moodle] and [gift] (https://docs.moodle.org/310/en/GIFT_format). Gift is simpler and widely used. moodle2amc converts [gift] questions text, but no answers. Options must be added by hand in a long and painful process.
Hope these issues are easy to solve.

**Comment by nennigb** [comment]
Hi,

  1. Accent in question name seems to generate error in amc gui (not at the tested latex stage):
```
Des défauts ont été détectés dans ce sujet. Corrigez-les dans le fichier source et mettez à jour les documents de travail.
Aucune case à cocher (Cela concerne 5 sujets, voir par exemple le numéro 1).
```
However I didn't notice problem for group name (can you provide an exemple of group name ?).
We will see how to sanitize these tags. Thank for reporting ;-)
Note you need also to avoid underscore.

  2. **Gift format is not supported by `amc2moodle`** and we didn't plan to support it (`moodle2amc` is based on XML processing). If you want to store or edit your questions in gift format, you can, but you need moodle to convert them back in XML to feed `amc2moodle`.

Benoit

**Comment by pacoriviere** [comment]
Thanks Benoit,
I may not have been clear enough. I am only speaking about xml format. I have only imported moodle questions in moodle xml format.
But in moodle xml files, questions seem to be stored in several ways. Questions can be created in moodle using html, moodle_auto_format, plain_text and markdown. ([1](https://docs.moodle.org/310/en/Moodle_XML_format#Text_formats)). Options created using html are properly imported to amc tex by moodle2amc scripts. But not moodle options using plain text. This happened with all xml moodle files converted, as every question can have a different text format,
See the sentence _"for each piece of content"_ in the reference.

**Comment by pacoriviere** [comment]
1. I had a moodle category called Màquines
It was converted to tex as
\element{Màquines}
Try any element with this name and it will fail to compile.
try
\element{Màquines}
and it will complie.

**Comment by nennigb** [comment]
The PR should do the job for the accents. You can test it if you want (by cloning the branch `fix-moodle2amc-question-label`).

For your question about moodle XML text format, it is _theoretically_ possible to do it. Today, only a html to latex parser is defined but other could be added. A way could be to use a python library to convert markdown into html and then reuse the previous workflow.
Do you want to contribute ? I didn't have time to work on it in the next weeks...

ps : I will add a comment in the readme to mention that only html format is supported today.

**Comment by nennigb** [comment]
A second PR #41 will add support for markdown formatted question.
I didn't add image support. Indeed, I am not sure that it is possible with plaintext editor (excepted from external links, that will not work, as is, with latex).

@pacoriviere  Could you try it from the branch `feature-moodle2amc-markdown` and tell me if it works for your quizzes ?

**Comment by nennigb** [comment]
It should work now. You can clone the master or get the new version (2.7) on pipy.
For all details, see the PR #41 and #40 notes.
