### ISSUE TITLE
Quality loss on pictures (pdf)

### ISSUE THREAD

**Issue by luclaurent** [nennigb/amc2moodle#39]
I observe a loss of quality on the pictures after the xml conversion (pdf file):

Original file:
![image](https://user-images.githubusercontent.com/147177/99415414-0ec93580-28f8-11eb-898a-779a8e9c36d4.png)

File in Moodle:
![image](https://user-images.githubusercontent.com/147177/99415336-fb1dcf00-28f7-11eb-9202-fd2356a4baab.png)

This is probably due to the `convert` process of Imagemagick.

**Comment by nennigb** [comment]
Hi,

Perhaps some resolution could be passed thanks to the magic comments to change a (non existing) default value.

B.
