### ISSUE TITLE
regression in translating < and > symbols: they are not output as &lt; and &gt; anymore

### ISSUE THREAD

**Issue by adl** [nennigb/amc2moodle#44]
Hi!

I recently had to reconvert a question I had successfully translated with an older version of amc2moodle, but the new version failed to render online.  My question had a large equation containing symbols < and >.  The produced XML output was incorrectly producing those symbols verbatim, instead of escaping them with &lt; and &gt;.  This in turn caused the online rendering of the question to be completely broken, because the browser would see opening tags in my equation when there was none, and then it would attempt to close those to fix things up.

I know that version 2.5.0 correctly escapes < and >, as this is the version I ended up using.  
Version 2.6.0 is broken in that regards.

In patch e02307b7864ec3643b753ef6e4c315ff742adb46, you can see the regression appearing in this snippet:
```diff
--- a/amc2moodle/amc2moodle/test/QCM.xml
+++ b/amc2moodle/amc2moodle/test/QCM.xml
@@ -91,7 +92,7 @@
     
   ]]></text></questiontext><answer format="html" fraction="33.333333333333336"><text><![CDATA[ Ou en <tt>C</tt> using <tt>alltt</tt> package
 <p><pre>
-int s=-2; <br/>for (int i=0;i&lt;4; i++)<text font="serif">{</text> <br/>s=i*i+s; <br/><text font="serif">}</text>
+int s=-2; <br/>for (int i=0;i<4; i++)<text font="serif">{</text> <br/>s=i*i+s; <br/><text font="serif">}</text>
 </pre></p>
 ]]></text></answer><answer format="html" fraction="33.333333333333336"><text><![CDATA[
            \(\lvert-10-2\rvert\)
```

**Comment by nennigb** [comment]
Thank you for reporting. I will have a look this week.
Could you provide a minimal LaTeX example to show exactly the problem ? 
The example you mention in QCM.xml render correctly in moodle (3.10) with `for (int i=0;i<4; i++)` in the CDATA field of the XML. What are your moodle version ?

**Comment by adl** [comment]
> Thank you for reporting. I will have a look this week.
> Could you provide a minimal LaTeX example to show exactly the problem (especially if in equation environnement)?

I think something as simple as `$w_1<w_2<\cdots<w_n$` was already causing a problem.

The larger equation I remember being broken was 

```
\begin{align*}
&D(i,j) = \\
&\begin{cases}
  0 &   \text{si }i>j\\
  w_i & \text{si }i=j \\
  \displaystyle\min\left\{\!D(i,k{-}1)+D(k{+}1,j)+\sum_{m=i}^{\smash{j}} w_m\middle| k\!\in\!\rangecc{i,j}\!\right\} &\text{si }i<j
\end{cases}
\end{align*}
```
where the final `i<j` was causing the reminder of the question to disappear.


> The example you mention in QCM.xml render correctly in moodle (3.10) with '`for (int i=0;i<4; i++)`' in the CDATA field of the XML.

I suspect that HTML tag names cannot start with digits, so `<4` would not pose any problem. But just replace `i<4` by `4<i` and you'll probably confuse your browser is lost.

In fact you don't really need Moodle to try that.  Just save the following code in a file, and display it in your browser: 

```html
<html>
  <body>
    <pre>
      for (int i=0;i<4; i++) <br/>
      for (int i=0;4&lt;i; i++) <br/>
      for (int i=0;4<i; i++) Where am I?<br/>
    </pre>
  </body>
</html>
```
In Firefox, Chromium, and w3m I see it rendered like this:
```
      for (int i=0;i<4; i++) 

      for (int i=0;4<i; i++) 

      for (int i=0;4

 ```

> What are your moodle version ?

Sorry, I could not find a place where this is displayed.

**Comment by nennigb** [comment]
For a quick fix, you can remove the `unescape` in `convert.py` (l. 824)
```
# Save output
s = unescape(etree.tostring(self.tree, pretty_print=True, encoding="utf-8").decode('utf-8'))
````
It should work for all questions **excepted calculated questions**. Indeed, for calculated question the <questiontext> is modified in python and the successive usage of xslt transform remove `CDATA` causing, this time, escaping the html elements (explaining the regression has been introduced).
Until now, I didn't see any elegant solution (parse again if calculated question...)...

**Comment by nennigb** [comment]
I find a way (not too ugly). I will do the PR tomorrow.

**Comment by nennigb** [comment]
@adl If you want to test with the branch `fix-escaping`...

**Comment by adl** [comment]
Works for me.  Thanks!
