### ISSUE TITLE
Changing <answernumbering> tag value 

### ISSUE THREAD

**Issue by FredRaimbault** [nennigb/amc2moodle#46]
Hi
is there any way to change the tag value <answernumbering> ? By default, it seems to be set to "abc". I would like to set it to none or "123". 
Fred

**Comment by nennigb** [comment]
Hi,

I suppose you want to convert latex QCM into moodle XML.

Yes, you can change it, but not (yet) from the tex file, neither from command line option...

You need to find the file `convert.py`, and to modify (close to line 47):
```python
# Else choose one in supported tag {'123', 'abc', 'iii', 'none', 'ABCD'}.
ANSWER_NUMBERING_FORMAT = 'abc'  # put '123' here
```
This change will be permanent and will apply for all questions in the quiz.

I will add this option, probably through magic comment, in the next weeks.

Benoit

**Comment by FredRaimbault** [comment]
thanks, it works by editing "convert.sty"
