### ISSUE TITLE
Suppress CompleMulti

### ISSUE THREAD

**Issue by FredRaimbault** [nennigb/amc2moodle#47]
Hi,
how to suppress the CompleMulti option that seems to be set to true by default ? 
I tried the AMC macro \AMCnoCompleteMulti but it is not recognized : _1 undefined macro[\AMCnoCompleteMulti]._
Fred

**Comment by nennigb** [comment]
Hi,

Yes, you can change it, but not (yet) from the tex file, neither from command line option...

You need to find the file `convert.py`, and to modify (close to line 47):

```python
# ajout amc_aucune si obligatoire"
amc_autocomplete = 1  # change to 0
amc_aucune = u"aucune de ces réponses n'est correcte"
```
This change will be permanent and will apply for all questions in the quiz.

I will add this option, probably through magic comments, in the next weeks.

Benoit

ps : let me know if it works...

**Comment by FredRaimbault** [comment]
Thanks this solves my problem.
