### ISSUE TITLE
Choosing the percentage of a score

### ISSUE THREAD

**Issue by FredRaimbault** [nennigb/amc2moodle#48]
Hi Benoit,

is there a way to choose the percentage of a score that applies to an answer?
For example in a true/false question, choosing 100% for a good response and -100% for the bad response.

Fred

**Comment by nennigb** [comment]
Hi,

It should work using the  amc native command  `\bareme` (or `\scoring` in english). These commands are interpreted by `amc2moodle` at **quiz** and **question level** only (answer level is skipped).

```latex
 % define question scoring
  \begin{questionmult}{Qmult:Aucune}  \bareme{e=-0.5,b=1,m=-1.,p=-0.5} % never put b<1,
    Quel fruit possède un noyau?
    \begin{reponseshoriz}[o] % keep answers order
      \mauvaise{La pomme}
      \mauvaise{La tomate}
      \mauvaise{Le Kiwi}
    \end{reponseshoriz}
    \explain{Fruits grow on trees $x^3$, most of the \emph{time}.}
%amc2moodle \AddXMLQElement{partiallycorrectfeedback}{This is \textbf{partially} correct !}
  \end{questionmult}
```
or 
```latex
% Define test level scoring
% e=incohérence; b=bonne; m=mauvaise; p planché (on ne descent pas en dessous)
\baremeDefautS{e=-0.5,b=1,m=-0.5}% never put b<1,
\baremeDefautM{e=-0.5,b=1,m=-0.25,p=-0.5}% never put b<1, with amc2moodle m, correspond to the grade if all the wrong answers are ticked, b correspond to the grade if all the good answers are ticked
```

More details on the usage of `amc2moodle` are given [here](https://github.com/nennigb/amc2moodle/blob/master/amc2moodle/amc2moodle/README.md) or in these [latex examples](https://github.com/nennigb/amc2moodle/tree/master/amc2moodle/amc2moodle/test).

Benoit

**Comment by FredRaimbault** [comment]
OK, I used the amc native command at question level and its works.
Thanks for all your responses and for this wonderful tools.
Best regards
Fred

**Comment by nennigb** [comment]
Glad it was helpful.
