### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by ricpelo** [nennigb/amc2moodle#84]
Installing `amc2moodle` using `pipx` on Debian GNU/Linux "trixie" I get the following error:

```
$ pipx install amc2moodle
  installed package amc2moodle 2.10.3, installed using Python 3.12.6
  These apps are now globally available
    - amc2moodle
    - moodle2amc
done! ✨ 🌟 ✨
$ amc2moodle
Traceback (most recent call last):
  File "/home/ricardo/.local/bin/amc2moodle", line 23, in <module>
    from amc2moodle.amc2moodle import amc2moodle_class as a2m
  File "/home/ricardo/.local/pipx/venvs/amc2moodle/lib/python3.12/site-packages/amc2moodle/amc2moodle/amc2moodle_class.py", line 30, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
```

**Comment by luclaurent** [comment]
Same behaviour on macos. [Probably due to depreciation of `distutils`](https://peps.python.org/pep-0632/)

**Comment by nennigb** [comment]
What is your version of python ?

**Comment by luclaurent** [comment]
Two solutions could be considered: 

- add `setuptools` as requirement: it includes `distutils`
- remove the use to `distutils` and replace it by `shutil` as we only need to use `copytree`: this change leads to remove `python 3.7` compatibility

**Comment by nennigb** [comment]
Python 3.7 is now unsupported (EOL june 2023), so it is not a big deal. The oldest still supported version is now 3.8.
I will have a look on your branch.
I didn't succeed to reproduce the original problem with pip, neither on my linux machine, neither on the CI.

**Comment by luclaurent** [comment]
With `pip` no issue probably due to the fact that `setuptools` is installed when you create a new environment. 
With `pipx` (`pip install pipx`) it does not work.

**Comment by nennigb** [comment]
OK, probably, I will check. In my python 3.12 install I can still `import disutils`, and I have `setuptools` installed...

Your modifications looks fine (see the comment in the code)
You can create a PR with a clean rebase on the master ;-)
In the CIs you can remove python 3.7
